name: Makefile CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build_all
      run: make build_all

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
